### ISSUE TITLE
please clarify semantics or add check?

### ISSUE THREAD

**Issue by ptrebert** [vembrane/vembrane#154]
Hi,
I just ran into the issue that this filter
```
vembrane filter '(is_hom_ref(s) for s in SAMPLES)' input.vcf
````
returned calls that were actually not hom ref calls. It took me a few seconds to realize that I was missing the `all()` here to aggregate the created iterable of bools into a single bool. Maybe there is a way to catch that situation and throw an error?

Without knowing the internals, it looks a bit like this happened:
```
if [False]:
    # evaluating to True because non-empty list
```

Best,
Peter

**Comment by tedil** [comment]
Hi Peter!

You correctly noticed that it didn't return the expected results because the bools generated in your expression weren't aggregated into a single bool (using e.g. `all` or `any`). 
The reason for this lies in Python's concept of truthy and falsy values, which can be found in the Python docs under [Truth Value Testing](https://docs.python.org/3/library/stdtypes.html#truth-value-testing).
In Python, any object is by default considered "truthy", e.g. `bool(some_object) is True`, as long as `some_object` does not define its own `__bool__` or `__len__` implementation.
Consequently, when your filter expression resulted in a [generator](https://docs.python.org/3/glossary.html#term-generator-expression) of booleans, it was considered truthy, leading to the unexpected behaviour you encountered.
```python
assert bool(True for _ in range(4)) is True      # because a generator object is truthy 
assert bool(False for _ in range(4)) is True     # same as above
assert bool(False for _ in range(0)) is True     # same as above
```
However, using a [list comprehension](https://docs.python.org/3/glossary.html#term-list-comprehension) instead, you'd get the following behaviour:
```python
assert bool([True for _ in range(4)]) is True    # because the list is not empty
assert bool([False for _ in range(4)]) is True   # same as above
assert bool([False for _ in range(0)]) is False  # because the list is empty
```

You suggested catching this scenario and possibly throwing an error. While that might seem like a good idea, it's not as straightforward as it appears. The filter expressions are entirely user-defined and can be any arbitrary, valid Python expression.
As a result, we can't make assumptions about how users intend to handle the results. There could be valid use cases where writing a filter making use of truthy values is precisely what's needed, and enforcing an error in such situations (which are not easy to detect anyways!) would be limiting.

I hope that wasn't too confusingly worded and helped you a little; if you have any more questions, just ask!
(Also let me know if I can close this issue)

**Comment by ptrebert** [comment]
Hi Till,
I appreciate the effort you put into your response, but boolean evaluation in Python is not really the point of my issue. My point is about finding the right trade-off between flexibility and user expectations (or hinting explicitly at what is happening under the hood in the docs).

In this case, my assumption was that `vembrane` would verify that the user's filter expression evaluates to type `bool` before (!) using the filter expression on the vcf records. Though this check should be straightforward to implement, I understand your point that some users may need that kind of flexibility. In which case, you may take this issue as a list of suggestions for future versions:
1. consider adding a parameter switch for strict vs relaxed (whatever the name ...) evaluation of the filter expression, with the default set to strict evaluation
2. my two cents about printing a warning message: could be quite annoying for those users who need that type of filter
3. update the docs with that caveat as long as point (1) is open. For example, extend the first line in the readme:
```
The filter expression can be any valid python expression that evaluates to bool.
Note that the evaluation rules in vembrane are exactly as in Python, e.g.,
a filter expression resulting in a non-empty list or set will evaluate to True,
and conversely, an empty list or set will evaluate to False.
``` 
4. update the docs with a non-contrived example illustrating a usecase where that feature leads to much more elegant filter expressions

Since you mentioned this issue in an enhancement already, I am going to close it.

Best,
Peter
